### ISSUE TITLE
Fail to load res_parser.bs.js: Should add "type": "module" in package.json

### ISSUE THREAD

**Issue by dsiu** [resinfo/rescript-parser#1]
```
node -v 
v16.14.2
rescript -v
9.1.4
```

```
(node:81891) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use node --trace-warnings ... to show where the warning was created)
/project/xxx/node_modules/@resinfo/parser/src/res_parser.bs.js:3
import * as Char from "rescript/lib/es6/char.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
```

**Comment by oliverfencott** [comment]
I'm not in front of my dev machine at the moment, but this library is designed to be used in the context of a ReScript project. Once you've run `yarn add @resinfo/parser`, you should then add it to your `bsconfig.json`, then add it to the `bs-dependencies` array. After that, run `yarn rescript clean` and then `yarn rescript build -with-deps` to build the project files; this should then build the project files to be in line with however you've set your `package-specs` in `bsconfig.json`.

Do you have a reproduction repo that I can check?

**Comment by dsiu** [comment]
I have created a template repo to showcase this.  `bsconfig.js` is set to compile `res` into `es6` module with `.bs.js` suffix.

https://github.com/dsiu/rescript-parser-es6

Running `main.bs.js` or invoking `ava` would should show a node error `SyntaxError: Cannot use import statement outside a module`

After looking into this more, it might not be `rescript-parer` specific.  Compiling `res` with `.mjs` prefix would work.

**Comment by oliverfencott** [comment]
That's correct, node natively supports ES modules only with `.mjs` files. The same applies for `require()`: you must use `.cjs` files if `"type"` is set to `"module"`.

**Comment by dsiu** [comment]
Thanks for confirming.  This is a non-issue and should be closed.  Thanks!
